### PR TITLE
Nitrogen Fingers Text Image Format

### PR DESCRIPTION
**Pull request by oeed**
This format is an existing format, so checking of the facts is more important rather than actually approving the topic.

### CODE REVIEW

**Comment by oeed** [comment]
@viluon whilst I too place space between brackets, I'm not really sure whether that styling should be used here as it's not overly common.

@SquidDev Yeah you're probably right there. If people don't understand how to do that they'll probably just use the premade API anyway.

**Comment by viluon** [comment]
@oeed I don't enforce the additional whitespace, but your code used different formatting at different places..

**Comment by oeed** [comment]
@viluon right.. so I did actually :stuck_out_tongue:

**Comment by demhydraz** [comment]
:+1: from me.

**Comment by viluon** [comment]
_bump_ can we accept this @oeed?

**Comment by oeed** [comment]
@viluon I'm still at her house and only have my phone, so I can't edit it right now, but I think we should actually move the character/byte section to teminology or something similar rather than having it in here. I might be home in a day or two, but if you are able to do it now we can merge it.

**Comment by viluon** [comment]
I'll unpack my backpack from the mountain trip and get right to it @oeed

**Comment by oeed** [comment]
Awesome!

**Pull request merged**
