### PR TITLE
Rednet Protocol

### PR DESCRIPTION
**Pull request by ghost**
here I restert the pull request for the rednet prorocol

### CODE REVIEW

**Comment by viluon** [comment]
`meta` This PR is a fix of the mess at #44.

**Comment by oeed** [comment]
Just a few formatting fixes @justsomeoneelseagain:
- All the table column and row names need to be capitalised (i.e. 'Transmission Method' not 'transmission method') and the other cells should begin with a capital letter (i.e. 'The target computer...' not 'the target computer...')
- ~~Any number values, variable types and variable names need to have backwards ticks `around them so they're formatted like this:`65535`~~ Nice work, I see you've actually already done that since I wrote this, maybe just add it around things like `table` and `number` too.

Again, I'm not at all knowledgable about Rednet, but can you explain the 'short name' and 'protocol ID'? Are they specified/used by anything particularly?

**Comment by ghost** [comment]
@oeed protocol ID is invented by me and supposed to be something like a MIME-Type for protocols. The short name is just a short variant of the name and the long is only words e.g. `HTTP` - `Hyper Text Transfer Protocol` , but the commonly used Name is `HTTP`, and the protocol is always referred in programming as `http`

**Comment by Luca0208** [comment]
This looks nice :+1:

**Comment by oeed** [comment]
@justsomeoneelseagain okay, we might need to decide whether they're needed. I can see benefits of having them, but we need to get that communication template #45 going.

**Comment by ghost** [comment]
@oeed , ok, short and long names are not really needed, but we need something to identify protocols (and it has to be a string)

I´ll work on a Template as soon as this got accepted and then PR some more Protocols

**Comment by oeed** [comment]
I'd say remove Short Name but keep Protocol ID.

This won't be accepted until a template is made and accepted so we don't need to update it. If you're going to make it, base it heavily off the file format template and only change what's needed.

**Comment by lyqyd** [comment]
> "The data to be transmitted, specified by the protocol"

Should this not be the sender specifying the message?  I'm not even sure what you're trying to say here.

This is also not a great naming scheme for this standard, since one would want to create standards for individual protocols intended to be transmitted over rednet, like TRoR.  We can call both of them protocols, but we then ought to make distinctions between transmission/transport protocols (like Rednet, GPS, or LyqydNet) and data protocols (like TRoR).

**Comment by oeed** [comment]
Yes actually that's quite true @lyqyd, this isn't a protocol but a method of transmission. @justsomeoneelseagain I'd just remove any references where you have called this a protocol. This also means removing the protocol ID.

**Comment by ghost** [comment]
I agree, Rednet isn´t a Protocol, the whole document has to be written new from scratch, I won´t do that.

**Pull request closed without merging**
