### PR TITLE
Fix a formatting issue in Terminology.md

### PR DESCRIPTION
**Pull request by demhydraz**
nice reviewing @oeed

### CODE REVIEW

**Comment by oeed** [comment]
This deserves an appropriate label.

**Comment by demhydraz** [comment]
... *sigh* just merge it

**Comment by oeed** [comment]
So no more cock-ups in there?

**Comment by demhydraz** [comment]
Nope.

**Comment by viluon** [comment]
Ehm, you let @demhydraz basically self-approve this @oeed. While in this case it's absolutely fine, this shouldn't happen in the future :confused:

**Comment by oeed** [comment]
@viluon it was just a brainfart we both overlooked and noticed, but the original PR certainly was, well, a cockup that I shouldn't let through.

**Pull request merged**
