### PR TITLE
How to Propose a Standard (Tutorial)

### PR DESCRIPTION
**Pull request by viluon**
A tutorial to get you started (currently work in progress). I am planning on moving tutorial-like stuff from the README into the new tutorial directory. What do you think?

### CODE REVIEW

**Comment by demhydraz** [comment]
Looks good :+1: - altho I would have stuck with your recommendations and only submitted the PR when it's done :stuck_out_tongue:

**Comment by oeed** [comment]
I'd propose mentioning a standard way to express file trees.

I suggest using = for folders and - for files and placing it within a code block, like this:

```
= documents
    - image.ucg
    - readme.txt
    = code
        - paint.lua
= system
    - startup

```

**Comment by demhydraz** [comment]
```
documents
└── image.ucg
└── readme.txt
└── code
       └── paint.lua
```

**Comment by oeed** [comment]
How do you differentiate files and folders though if the folder is empty?

**Comment by demhydraz** [comment]
Postfix the entry with it's mime type.

**Comment by viluon** [comment]
Nice suggestion @oeed, I like it better than yours @demhydraz, sorry :stuck_out_tongue: I'll add it to the guide.

**Comment by viluon** [comment]
@oeed use space or tab indent for the directory tree? I'd suggest tab indentation.

**Comment by demhydraz** [comment]
Tab indentation.

**Comment by viluon** [comment]
:+1:

**Comment by oeed** [comment]
Yeah tabs, might've just been my Markdown editor (not Sublime this time).

**Comment by demhydraz** [comment]
Is this not going to be merged? It looks quite done from my point of view.

**Comment by viluon** [comment]
Finally resolved conflicts with `master`.

**Comment by demhydraz** [comment]
:+1:

**Comment by oeed** [comment]
I'll leave this branch undeleted if there's anything you want to add @viluon, but otherwise feel free to delete it.

**Pull request merged**
