### PR TITLE
Rednet Documentation

### PR DESCRIPTION
**Pull request by ghost**
Adds Rednet Standard Documentation as a base for other Communication Standards

### CODE REVIEW

**Comment by oeed** [comment]
Awesome, nice work @justsomeoneelseagain! I haven't really used Rednet much so I'm not really too sure about the content, but it looks like it's pretty complete.

There are a few formatting issues though. As this is the first communication standard we'll need to create a template similar to the file format one, see #45 for that.

**Comment by ghost** [comment]
@oeed Ok, I´ll trie to add that

**Comment by ghost** [comment]
@oeed all the data  is from the ComputerCraft.jar in assets/lua/rom from the rednet API and the repeater script

**Comment by ghost** [comment]
dns is in the rednet api too

**Comment by viluon** [comment]
Thanks for the work @justsomeoneelseagain, I'd say the docs need a little polishing before we can merge this. I've already opened [a PR](https://github.com/justsomeoneelseagain/CraftOS-Standards/pull/1) on [your fork](https://github.com/justsomeoneelseagain/CraftOS-Standards) to fix the typo in the file name ("DNS-Protococ.md"), and I will continue to open PRs as I review the contents.

**Comment by ghost** [comment]
Thank you @viluon . I tried to get the head table a bit better now.

**Comment by viluon** [comment]
Thanks for the updates @justsomeoneelseagain! A couple of things:
- **Don't hurry!** Even if you complete the docs today it will take at least a week before your standard receives general approval and we can merge it. You don't have to rush yourself to complete the standard documents as soon as possible :wink: 
- **Quality is more than quantity.** Take time and think carefully about what you are writing down. If accepted, these files _you_ authored are going to rest in this repository _forever_!
- **Try to comment your commits.** It is always a good idea to comment the commits with something more descriptive than just "Update foo" or "Create bar". Try to summarize what you've changed. That way everyone will see what's going on right now without having to dig through the diffs!
- **I'll help you out.** I've self-assigned your PR, and I'll review all of your proposed changes. If there are some problems, I'll tell you and probably even propose fixes to the new files on your fork. When in need of any help, feel free to contact me on our [Gitter chat](https://gitter.im/oeed/CraftOS-Standards) :wink:

**Comment by ghost** [comment]
can someone please reject this pull request, I made anoter branch just for rednet, because in this branch there are things that don´t belong to this pull request, i´ll make a correct pull request after this got re.ected

**Comment by ghost** [comment]
oh, i can close it

**Comment by ghost** [comment]
oops

**Comment by demhydraz** [comment]
>  Don't hurry! Even if you complete the docs today it will take at least a week before your standard receives general approval and we can merge it. You don't have to rush yourself to complete the standard documents as soon as possible :wink: 

Aren't existing standards exempt of the community approval?

**Comment by viluon** [comment]
True that, @demhydraz. On the other hand, more than one person should always review a proposal before it can be accepted, and that takes time. There's no need to hurry. As I said, quality is much more important than quantity (or speed, in this case).

**Pull request closed without merging**
