### PR TITLE
Fix Plain Text Typo

### PR DESCRIPTION
**Pull request by Luca0208**

### CODE REVIEW

**Comment by ghost** [comment]
You´re right. Can someone merge it? @oeed @viluon

**Comment by Luca0208** [comment]
Seems like no-one(with write permissions) is online right now :/ well, sooner or later someone will see this

**Comment by viluon** [comment]
@Luca0208 and @justsomeoneelseagain, please note that GitHub Issues aren't a place for chat. There's no need stating the obvious (no offence intended):

> well, sooner or later someone will see this

As for the PR itself, thanks for pointing this out. Generally, updates to any standards are not permitted, but I think we can allow it this time @oeed.

**Comment by oeed** [comment]
@viluon I'd say updates that change what the format is aren't allowed, but formatting changes are fine.

**Pull request merged**
