### PR TITLE
Switch to MIME Type-based Repository Structure

### PR DESCRIPTION
**Pull request by ghost**
So, this sorts the file formats by their MIME-Type and adds a table to the README.md. (and moves the template for file formats into the file formats folder and calls it TEMPLATE.md) (And it Renames the Folder 'File Formats' in 'File-Formats' because on the GitHub Website you aren't able to create or move to a Folder which contains a space in its name)
- [x] Move and rename File Formats
- [x] Move and rename the Template
- [x] Move the Recommendations into the File Formats README.md
- [x] Reciveve General Approvement

---

This Pull Request is releated to #46 .

### CODE REVIEW

**Comment by oeed** [comment]
Yeah I quite like this structuring, nice job :+1:

**Comment by ghost** [comment]
@oeed , do you have ideas for the descriptions?

**Comment by demhydraz** [comment]
:+1: from me too

**Comment by viluon** [comment]
Hold on @oeed, we need to merge #13 first or we'll get collisions on the `tutorial` branch!

**EDIT**: Also, I think that you should change "Recommendations" to "Use Cases" (or something similar) @justsomeoneelseagain, sounds more descriptive imo.

**Comment by Luca0208** [comment]
I really like this too :+1:

**Comment by ghost** [comment]
This is no longer WIP, if there aren´t any suggestions.

**Comment by viluon** [comment]
> This is no longer WIP, if there aren´t any suggestions.

Please leave that on the mods, they know how to handle labels :wink:

**Comment by lyqyd** [comment]
Are we back to text/lua now, or are the lua/table, etc. set yet to be merged?

**Comment by oeed** [comment]
@lyqyd, yes, mainly due the objections with #39. @viluon we need to make a decision on that.

**Comment by oeed** [comment]
@demhydraz or @viluon I'm not expert with conflict resolution at all, how do we fix this?

**Comment by demhydraz** [comment]
Merge, files will be left with conflicts, write those off, boom.

**Comment by lyqyd** [comment]
If we're ready to merge this but simply need to resolve the merge conflicts, I can take care of that tonight or tomorrow.  @oeed, @viluon, anything else we need to do other than simply fix the merge?  This appears to have general approval.

**Comment by viluon** [comment]
Whoa, thanks for the bump @lyqyd, totally forgot about this :confused: I don't think anyone is against this, if you could fix the conflicts, that would be great! Then we'd be good to go. I'd help you out but am busy this week.

**Comment by oeed** [comment]
Agreed @viluon

**Comment by lyqyd** [comment]
Okay, I've manually merged this, so we should be good go to.

**Pull request merged**
